name: Build and Deploy

on:
  push:
    branches:
      - main

jobs
  build_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          # Comandos para construir el proyecto
      - name: Send notification
        uses: my-custom-action/send-email@v1
        with:
          to: example@example.com
          message: "Build successful!"


  # Build Docker image and push to Docker Hub
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t my-app .
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: docker push my-app

  # Deploy to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./public

  # Optimize workflow execution by caching npm dependencies
  optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  # Send failure notification if build fails
  notification:
    runs-on: ubuntu-latest
    needs: [build]
    if: failure()
    steps:
      - name: Send failure notification
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const issueComment = context.issue({ body: 'The build failed. Please check.' });
            await github.issues.createComment(issueComment);

  # Execute a workflow specific to feature branches on pull requests
  feature_pr_workflow:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref, 'feature/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add additional steps as needed for feature PR workflow

